name: mahmoud_atef
description: Mahmoud Atef - Flutter & Mobile App Developer Portfolio
version: 0.0.1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  jaspr: ^0.22.0
  jaspr_router: ^0.8.1

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.4.13
  jaspr_builder: ^0.22.0
  jaspr_tailwind: ^0.3.6
  lints: ^5.0.0

jaspr:
  mode: static
  base: /mahmoud_atef/
